### PR TITLE
fix participation for relocated teams, resolve #80

### LINKED ISSUE #80: [BUG] Oakland participation data missing for offense 2016-2019
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

1.3.2.2

### Describe the bug

Offensive player participation data is missing for Oakland from years 2016-2019.
It is present from 2020 onwards for Las Vegas.
Defensive player participation data is present.
Suspect an issue cropped up with the Team name change

### Reprex

```r
r
participation_test <- nflreadr::load_participation(2018) |> filter(possession_team == "OAK")

```
```


### Expected Behavior

What happens
![image](https://user-images.githubusercontent.com/88771954/236750686-39317de1-5e15-495d-b0d4-219609374dbf.png)
What should happen
![image](https://user-images.githubusercontent.com/88771954/236750793-8829525f-d5fc-4006-8354-06d639eab92d.png)


### nflverse_sitrep

```r
> nflverse::nflverse_sitrep()
── System Info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• R version 4.2.1 (2022-06-23 ucrt)   • Running under: Windows 10 x64 (build 22621)
── nflverse Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• nflreadr (1.3.2.02)    • nflseedR (1.2.0)       • nflplotR (1.1.0.9004)  
• nflfastR (4.5.1.9001)  • nfl4th   (1.0.2.9006)  • nflverse (1.0.2)       
── nflverse Options ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
No options set for nflreadr, nflfastR, nflseedR, nfl4th, nflplotR, and nflverse
── nflverse Dependencies ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• askpass     (1.1)     • hms        (1.1.2)    • progressr    (0.13.0)   
• cachem      (1.0.6)   • httr       (1.4.4)    • proto        (1.0.0)    
• cli         (3.6.0)   • isoband    (0.2.7)    • purrr        (1.0.1)    
• codetools   (0.2-18)  • janitor    (2.2.0)    • R6           (2.5.1)    
• colorspace  (2.1-0)   • jsonlite   (1.8.4)    • rappdirs     (0.3.3)    
• cpp11       (0.4.3)   • labeling   (0.4.2)    • RColorBrewer (1.1-3)    
• crayon      (1.5.2)   • lattice    (0.20-45)  • Rcpp         (1.0.10)   
• curl        (5.0.0)   • lifecycle  (1.0.3)    • rlang        (1.1.0)    
• data.table  (1.14.8)  • listenv    (0.9.0)    • rstudioapi   (0.14)     
• digest      (0.6.31)  • lubridate  (1.9.2)    • scales       (1.2.1)    
• dplyr       (1.1.0)   • magick     (2.7.3)    • snakecase    (0.11.0)   
• fansi       (1.0.4)   • magrittr   (2.0.3)    • stringi      (1.7.12)   
• farver      (2.1.1)   • MASS       (7.3-57)   • stringr      (1.5.0)    
• fastmap     (1.1.0)   • Matrix     (1.5-3)    • sys          (3.4.1)    
• fastrmodels (1.0.2)   • memoise    (2.0.1)    • tibble       (3.2.1)    
• furrr       (0.3.1)   • mgcv       (1.8-40)   • tidyr        (1.3.0)    
• future      (1.31.0)  • mime       (0.12)     • tidyselect   (1.2.0)    
• generics    (0.1.3)   • munsell    (0.5.0)    • timechange   (0.2.0)    
• ggplot2     (3.4.1)   • nlme       (3.1-157)  • utf8         (1.2.3)    
• globals     (0.16.2)  • openssl    (2.0.5)    • vctrs        (0.6.2)    
• glue        (1.6.2)   • parallelly (1.34.0)   • viridisLite  (0.4.1)    
• gsubfn      (0.7)     • pillar     (1.8.1)    • withr        (2.5.0)    
• gtable      (0.3.1)   • pkgconfig  (2.0.3)    • xgboost      (1.7.3.1)  
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

### Screenshots

_No response_

### Additional context

You're a bunch of legends :)

### PR DESCRIPTION
**Pull request by john-b-edwards**

### CODE REVIEW

File: R/update_pbp_participation.R [hunk 1]
```diff
@@ -73,11 +73,14 @@ pbp_participation <-
         number_of_pass_rushers,
         players_on_play
       ) |>
+      # oak -> lv exception
+      dplyr::mutate(tmp_possession_team = dplyr::case_when(possession_team == "OAK" ~ "LV",
```
Comment (tanho63) [inline R/update_pbp_participation.R:77]: Maybe more long term robust to use nflreadr:clean_team_abbrs()?

Comment (mrcaseb) [reply R/update_pbp_participation.R:77]: I agree here. 

`nflreadr::clean_team_abbrs(possession_team, current_location = TRUE, keep_non_matches = TRUE)`

would be more robust in case of future team abbreviation changes. 

The current solution looks fine imo. It's just less robust

Comment (john-b-edwards) [reply R/update_pbp_participation.R:77]: Much better, wasn't familiar with that particular function. Thanks for the tip!

**Review by mrcaseb — APPROVED** [review]
looks good to me, thanks!
